-- Existing demo slugs: never overwrite an existing record.
insert into public.experiencias (id,nombre,categoria,descripcion,detalle,zona,duracion,precio,filtros,imagen,alt,incluye,estado) values
('juegos','Noche de juegos y pizza','Una mesa, mil anécdotas','Juegos de mesa y desafíos para compartir. La mejor jugada es venir con ganas de reírte.','Una noche para desconectar de las pantallas y conectar alrededor de una mesa. Probá juegos cooperativos, armá equipos y compartí una pizza entre rondas. No necesitás experiencia previa.','Palermo, CABA','3 horas',18000,array['Con amigos','Conocer gente'],'juegos','Un grupo de amigos se ríe mientras juega alrededor de una mesa.',array['Juegos de mesa y desafíos guiados','Pizza para compartir','Bebida sin alcohol'],'publicado'),
('cocina','Cocina en equipo','Manos a la masa','Preparar pastas desde cero, aprender algo nuevo y sentarse a disfrutarlo juntos.','Amasá, probá y descubrí el gusto de cocinar en compañía. La propuesta comienza con la preparación de pastas y termina con una mesa compartida. Una experiencia pensada también para quienes recién empiezan.','Villa Crespo, CABA','3 horas',32000,array['Con amigos','En pareja'],'cocina','Dos personas preparan pasta fresca en una cocina.',array['Ingredientes y utensilios','Actividad guiada de pastas','Comida compartida y bebida sin alcohol'],'publicado'),
('pintura','Pintura y mocktails','Un poco de color','Una tarde creativa, pinceles y bebidas sin alcohol. No hace falta saber pintar.','Dejá que los colores marquen el ritmo. Explorá técnicas simples, charlá y creá una pieza propia mientras disfrutás de un mocktail. Acá importa el proceso, no pintar perfecto.','Chacarita, CABA','2 horas',24000,array['En pareja','Conocer gente'],'pintura','Una mesa compartida con acuarelas, pinceles y dibujos en proceso.',array['Materiales de pintura','Acompañamiento creativo','Un mocktail sin alcohol'],'publicado'),
('picnic','Picnic al atardecer','Aire libre, buena compañía','Una merienda, actividades grupales y ese ratito en el que el día baja un cambio.','Una pausa al aire libre para compartir algo rico, conversar y sumarte a juegos grupales tranquilos. La propuesta está pensada para disfrutar de la compañía y el atardecer. Su realización dependería del clima.','Zona norte, Buenos Aires','2 horas',15000,array['Con amigos','En pareja','Conocer gente'],'picnic','Un grupo comparte un picnic al aire libre junto al agua.',array['Merienda y bebida sin alcohol','Mantas para compartir','Actividades grupales'],'publicado'),
('trivia','Trivia de películas','Para protagonistas de equipo','Equipos, preguntas y desafíos de cine. Hay lugar para cinéfilos y espectadores casuales.','Desde escenas inolvidables hasta bandas sonoras: una propuesta para poner a prueba la memoria en equipo. Las rondas mezclan preguntas y desafíos para que todos puedan participar.','Almagro, CABA','2 horas',16000,array['Con amigos','Conocer gente'],'trivia','Amigos comparten pizza y una tarde de entretenimiento en un sillón.',array['Rondas de preguntas y desafíos','Coordinación de equipos','Snack y bebida sin alcohol'],'publicado'),
('sabores','Ruta de sabores','Salir a probar algo distinto','Un recorrido por distintas propuestas gastronómicas, para descubrir de a bocados.','Caminá, conversá y explorá diferentes sabores en un recorrido gastronómico compartido. Este itinerario es ficticio: no representa locales ni paradas confirmadas.','San Telmo, CABA','3 horas',35000,array['En pareja','Conocer gente'],'sabores','Amigos conversan y comparten diferentes platos en una mesa.',array['Recorrido acompañado','Tres degustaciones ilustrativas','Bebida sin alcohol'],'publicado')
on conflict (id) do nothing;
